version: '3.5'

services:
  laravel-app:
    build:
      context: './Dockerfile'
      args:
        uid: 123
    container_name: XXXXXXXXXXXX
    ports:
      - XXXX:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./html:/var/www/html
      # - ./apache2:/etc/apache2/
    networks:
      backend:
        aliases:
          - app

  mysql-db-laravel:
    image: mysql:5.7
    container_name: XXXXXXXXx
    volumes:
      - ./mysql_home:/root/
    environment:
      - MYSQL_ROOT_PASSWORD=XXXXXXX
      - MYSQL_DATABASE=XXXXXXXX
      - MYSQL_USER=XXXXXXXX
      - MYSQL_PASSWORD=XXXXXXXX
    networks:
      backend:
        aliases:
          - mysql-db-laravel

networks:
  backend:
    name: backend-network